package com.yaoyou.model.dataObject;

import java.math.BigDecimal;
import java.util.Date;

public class ActivityItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY_ITEM.ACTIVITY_ID
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY_ITEM.ITEM_ID
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY_ITEM.ACTIVITY_PRICE
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    private BigDecimal activityPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY_ITEM.ACTIVITY_POINT
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    private Integer activityPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY_ITEM.DESCRIPTION
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ACTIVITY_ITEM.CREATE_TIME
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY_ITEM.ACTIVITY_ID
     *
     * @return the value of ACTIVITY_ITEM.ACTIVITY_ID
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY_ITEM.ACTIVITY_ID
     *
     * @param activityId the value for ACTIVITY_ITEM.ACTIVITY_ID
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY_ITEM.ITEM_ID
     *
     * @return the value of ACTIVITY_ITEM.ITEM_ID
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY_ITEM.ITEM_ID
     *
     * @param itemId the value for ACTIVITY_ITEM.ITEM_ID
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY_ITEM.ACTIVITY_PRICE
     *
     * @return the value of ACTIVITY_ITEM.ACTIVITY_PRICE
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public BigDecimal getActivityPrice() {
        return activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY_ITEM.ACTIVITY_PRICE
     *
     * @param activityPrice the value for ACTIVITY_ITEM.ACTIVITY_PRICE
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public void setActivityPrice(BigDecimal activityPrice) {
        this.activityPrice = activityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY_ITEM.ACTIVITY_POINT
     *
     * @return the value of ACTIVITY_ITEM.ACTIVITY_POINT
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public Integer getActivityPoint() {
        return activityPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY_ITEM.ACTIVITY_POINT
     *
     * @param activityPoint the value for ACTIVITY_ITEM.ACTIVITY_POINT
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public void setActivityPoint(Integer activityPoint) {
        this.activityPoint = activityPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY_ITEM.DESCRIPTION
     *
     * @return the value of ACTIVITY_ITEM.DESCRIPTION
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY_ITEM.DESCRIPTION
     *
     * @param description the value for ACTIVITY_ITEM.DESCRIPTION
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ACTIVITY_ITEM.CREATE_TIME
     *
     * @return the value of ACTIVITY_ITEM.CREATE_TIME
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ACTIVITY_ITEM.CREATE_TIME
     *
     * @param createTime the value for ACTIVITY_ITEM.CREATE_TIME
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}