package com.yaoyou.model.dataObject;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.ADDRESS_ID
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.USER_ID
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.NAME
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.PROVINCE
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.CITY
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.COUNTY
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.DETAIL
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.MOBILE
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.EMAIL
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.IS_DEFAULT
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADDRESS.TAG
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.ADDRESS_ID
     *
     * @return the value of ADDRESS.ADDRESS_ID
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.ADDRESS_ID
     *
     * @param addressId the value for ADDRESS.ADDRESS_ID
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.USER_ID
     *
     * @return the value of ADDRESS.USER_ID
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.USER_ID
     *
     * @param userId the value for ADDRESS.USER_ID
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.NAME
     *
     * @return the value of ADDRESS.NAME
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.NAME
     *
     * @param name the value for ADDRESS.NAME
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.PROVINCE
     *
     * @return the value of ADDRESS.PROVINCE
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.PROVINCE
     *
     * @param province the value for ADDRESS.PROVINCE
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.CITY
     *
     * @return the value of ADDRESS.CITY
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.CITY
     *
     * @param city the value for ADDRESS.CITY
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.COUNTY
     *
     * @return the value of ADDRESS.COUNTY
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.COUNTY
     *
     * @param county the value for ADDRESS.COUNTY
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.DETAIL
     *
     * @return the value of ADDRESS.DETAIL
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.DETAIL
     *
     * @param detail the value for ADDRESS.DETAIL
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.MOBILE
     *
     * @return the value of ADDRESS.MOBILE
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.MOBILE
     *
     * @param mobile the value for ADDRESS.MOBILE
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.EMAIL
     *
     * @return the value of ADDRESS.EMAIL
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.EMAIL
     *
     * @param email the value for ADDRESS.EMAIL
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.IS_DEFAULT
     *
     * @return the value of ADDRESS.IS_DEFAULT
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.IS_DEFAULT
     *
     * @param isDefault the value for ADDRESS.IS_DEFAULT
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault == null ? null : isDefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADDRESS.TAG
     *
     * @return the value of ADDRESS.TAG
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADDRESS.TAG
     *
     * @param tag the value for ADDRESS.TAG
     *
     * @mbggenerated Tue Aug 23 10:36:51 CST 2016
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}