package com.yaoyou.model.dataObject;

public class MedicineRemindRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEDICINE_REMIND_RECORD.ID
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEDICINE_REMIND_RECORD.USER_ID
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEDICINE_REMIND_RECORD.TIME
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MEDICINE_REMIND_RECORD.MEDICINE_NAME
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    private String medicineName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEDICINE_REMIND_RECORD.ID
     *
     * @return the value of MEDICINE_REMIND_RECORD.ID
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEDICINE_REMIND_RECORD.ID
     *
     * @param id the value for MEDICINE_REMIND_RECORD.ID
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEDICINE_REMIND_RECORD.USER_ID
     *
     * @return the value of MEDICINE_REMIND_RECORD.USER_ID
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEDICINE_REMIND_RECORD.USER_ID
     *
     * @param userId the value for MEDICINE_REMIND_RECORD.USER_ID
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEDICINE_REMIND_RECORD.TIME
     *
     * @return the value of MEDICINE_REMIND_RECORD.TIME
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEDICINE_REMIND_RECORD.TIME
     *
     * @param time the value for MEDICINE_REMIND_RECORD.TIME
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MEDICINE_REMIND_RECORD.MEDICINE_NAME
     *
     * @return the value of MEDICINE_REMIND_RECORD.MEDICINE_NAME
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String getMedicineName() {
        return medicineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MEDICINE_REMIND_RECORD.MEDICINE_NAME
     *
     * @param medicineName the value for MEDICINE_REMIND_RECORD.MEDICINE_NAME
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public void setMedicineName(String medicineName) {
        this.medicineName = medicineName == null ? null : medicineName.trim();
    }
}