package com.yaoyou.model.dataObject;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ORDER_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.STATE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.TYPE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.USER_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.TOTAL_PRICE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.PAY_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private Integer payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.ADD_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private Integer addId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.DISTRIBUTION_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private Integer distributionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.CREATE_TIME
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ORDER_ID
     *
     * @return the value of t_order.ORDER_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ORDER_ID
     *
     * @param orderId the value for t_order.ORDER_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.STATE
     *
     * @return the value of t_order.STATE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.STATE
     *
     * @param state the value for t_order.STATE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.TYPE
     *
     * @return the value of t_order.TYPE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.TYPE
     *
     * @param type the value for t_order.TYPE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.USER_ID
     *
     * @return the value of t_order.USER_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.USER_ID
     *
     * @param userId the value for t_order.USER_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.TOTAL_PRICE
     *
     * @return the value of t_order.TOTAL_PRICE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.TOTAL_PRICE
     *
     * @param totalPrice the value for t_order.TOTAL_PRICE
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.PAY_ID
     *
     * @return the value of t_order.PAY_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.PAY_ID
     *
     * @param payId the value for t_order.PAY_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.ADD_ID
     *
     * @return the value of t_order.ADD_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public Integer getAddId() {
        return addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.ADD_ID
     *
     * @param addId the value for t_order.ADD_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setAddId(Integer addId) {
        this.addId = addId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.DISTRIBUTION_ID
     *
     * @return the value of t_order.DISTRIBUTION_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public Integer getDistributionId() {
        return distributionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.DISTRIBUTION_ID
     *
     * @param distributionId the value for t_order.DISTRIBUTION_ID
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setDistributionId(Integer distributionId) {
        this.distributionId = distributionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.CREATE_TIME
     *
     * @return the value of t_order.CREATE_TIME
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.CREATE_TIME
     *
     * @param createTime the value for t_order.CREATE_TIME
     *
     * @mbggenerated Thu Aug 25 16:14:11 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}