package com.yaoyou.model.dataObject;

public class PointsNew {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.OGR_FID
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private Integer ogrFid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.SHAPE
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private byte[] shape;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.osm_id
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String osmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.name
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.barrier
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String barrier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.highway
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String highway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.ref
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String ref;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.address
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.is_in
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String isIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.place
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String place;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.man_made
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String manMade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_new.other_tags
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    private String otherTags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.OGR_FID
     *
     * @return the value of points_new.OGR_FID
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public Integer getOgrFid() {
        return ogrFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.OGR_FID
     *
     * @param ogrFid the value for points_new.OGR_FID
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setOgrFid(Integer ogrFid) {
        this.ogrFid = ogrFid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.SHAPE
     *
     * @return the value of points_new.SHAPE
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public byte[] getShape() {
        return shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.SHAPE
     *
     * @param shape the value for points_new.SHAPE
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setShape(byte[] shape) {
        this.shape = shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.osm_id
     *
     * @return the value of points_new.osm_id
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getOsmId() {
        return osmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.osm_id
     *
     * @param osmId the value for points_new.osm_id
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setOsmId(String osmId) {
        this.osmId = osmId == null ? null : osmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.name
     *
     * @return the value of points_new.name
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.name
     *
     * @param name the value for points_new.name
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.barrier
     *
     * @return the value of points_new.barrier
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getBarrier() {
        return barrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.barrier
     *
     * @param barrier the value for points_new.barrier
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setBarrier(String barrier) {
        this.barrier = barrier == null ? null : barrier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.highway
     *
     * @return the value of points_new.highway
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getHighway() {
        return highway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.highway
     *
     * @param highway the value for points_new.highway
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setHighway(String highway) {
        this.highway = highway == null ? null : highway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.ref
     *
     * @return the value of points_new.ref
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getRef() {
        return ref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.ref
     *
     * @param ref the value for points_new.ref
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setRef(String ref) {
        this.ref = ref == null ? null : ref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.address
     *
     * @return the value of points_new.address
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.address
     *
     * @param address the value for points_new.address
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.is_in
     *
     * @return the value of points_new.is_in
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getIsIn() {
        return isIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.is_in
     *
     * @param isIn the value for points_new.is_in
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setIsIn(String isIn) {
        this.isIn = isIn == null ? null : isIn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.place
     *
     * @return the value of points_new.place
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.place
     *
     * @param place the value for points_new.place
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.man_made
     *
     * @return the value of points_new.man_made
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getManMade() {
        return manMade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.man_made
     *
     * @param manMade the value for points_new.man_made
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setManMade(String manMade) {
        this.manMade = manMade == null ? null : manMade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_new.other_tags
     *
     * @return the value of points_new.other_tags
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String getOtherTags() {
        return otherTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_new.other_tags
     *
     * @param otherTags the value for points_new.other_tags
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public void setOtherTags(String otherTags) {
        this.otherTags = otherTags == null ? null : otherTags.trim();
    }
}