package com.yaoyou.model.dataObject;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import java.util.Date;

@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class ShopMedicine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.SHOP_MEDICINE_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private String shopMedicineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.PRICE
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.STORAGE_COUNT
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private Integer storageCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.SHOP_INFO_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private String shopInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.MEDICINE_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private String medicineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.CREATE_USER_NAME
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.CREATE_TIME
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_MEDICINE.CREATE_USER_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    private String createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.SHOP_MEDICINE_ID
     *
     * @return the value of SHOP_MEDICINE.SHOP_MEDICINE_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public String getShopMedicineId() {
        return shopMedicineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.SHOP_MEDICINE_ID
     *
     * @param shopMedicineId the value for SHOP_MEDICINE.SHOP_MEDICINE_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setShopMedicineId(String shopMedicineId) {
        this.shopMedicineId = shopMedicineId == null ? null : shopMedicineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.PRICE
     *
     * @return the value of SHOP_MEDICINE.PRICE
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.PRICE
     *
     * @param price the value for SHOP_MEDICINE.PRICE
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.STORAGE_COUNT
     *
     * @return the value of SHOP_MEDICINE.STORAGE_COUNT
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public Integer getStorageCount() {
        return storageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.STORAGE_COUNT
     *
     * @param storageCount the value for SHOP_MEDICINE.STORAGE_COUNT
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setStorageCount(Integer storageCount) {
        this.storageCount = storageCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.SHOP_INFO_ID
     *
     * @return the value of SHOP_MEDICINE.SHOP_INFO_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public String getShopInfoId() {
        return shopInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.SHOP_INFO_ID
     *
     * @param shopInfoId the value for SHOP_MEDICINE.SHOP_INFO_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setShopInfoId(String shopInfoId) {
        this.shopInfoId = shopInfoId == null ? null : shopInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.MEDICINE_ID
     *
     * @return the value of SHOP_MEDICINE.MEDICINE_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public String getMedicineId() {
        return medicineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.MEDICINE_ID
     *
     * @param medicineId the value for SHOP_MEDICINE.MEDICINE_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setMedicineId(String medicineId) {
        this.medicineId = medicineId == null ? null : medicineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.CREATE_USER_NAME
     *
     * @return the value of SHOP_MEDICINE.CREATE_USER_NAME
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.CREATE_USER_NAME
     *
     * @param createUserName the value for SHOP_MEDICINE.CREATE_USER_NAME
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.CREATE_TIME
     *
     * @return the value of SHOP_MEDICINE.CREATE_TIME
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.CREATE_TIME
     *
     * @param createTime the value for SHOP_MEDICINE.CREATE_TIME
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_MEDICINE.CREATE_USER_ID
     *
     * @return the value of SHOP_MEDICINE.CREATE_USER_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_MEDICINE.CREATE_USER_ID
     *
     * @param createUserId the value for SHOP_MEDICINE.CREATE_USER_ID
     *
     * @mbggenerated Wed Jul 20 13:40:46 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }
}