package com.yaoyou.model.dataObject;

import com.yaoyou.util.gps.GPS;
import org.codehaus.jackson.map.annotate.JsonSerialize;

import java.math.BigDecimal;
import java.util.Date;

@JsonSerialize(include= JsonSerialize.Inclusion.NON_NULL)
public class ShopInfo implements GPS {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.SHOP_INFO_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String shopInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.SHOP_NAME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.ORDER_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private Integer seq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.SHOP_ADDRESS
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String shopAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.SHOP_TEL
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String shopTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.IS_SEND
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String isSend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.IMG_URL
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.GPS_X
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private BigDecimal gpsX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.GPS_Y
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private BigDecimal gpsY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.STATE
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.CREATE_USER_NAME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.CREATE_TIME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.CREATE_USER_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_INFO.AVG_RATE
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    private BigDecimal avgRate;

    public BigDecimal getDistance() {
        return distance;
    }

    public void setDistance(BigDecimal distance) {
        this.distance = distance;
    }

    private BigDecimal distance;




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.SHOP_INFO_ID
     *
     * @return the value of SHOP_INFO.SHOP_INFO_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getShopInfoId() {
        return shopInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.SHOP_INFO_ID
     *
     * @param shopInfoId the value for SHOP_INFO.SHOP_INFO_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setShopInfoId(String shopInfoId) {
        this.shopInfoId = shopInfoId == null ? null : shopInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.SHOP_NAME
     *
     * @return the value of SHOP_INFO.SHOP_NAME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.SHOP_NAME
     *
     * @param shopName the value for SHOP_INFO.SHOP_NAME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setShopName(String shopName) {
        this.shopName = shopName == null ? null : shopName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.ORDER_ID
     *
     * @return the value of SHOP_INFO.ORDER_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public Integer getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.ORDER_ID
     *
     * @param orderId the value for SHOP_INFO.ORDER_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setSeq(Integer orderId) {
        this.seq = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.SHOP_ADDRESS
     *
     * @return the value of SHOP_INFO.SHOP_ADDRESS
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getShopAddress() {
        return shopAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.SHOP_ADDRESS
     *
     * @param shopAddress the value for SHOP_INFO.SHOP_ADDRESS
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setShopAddress(String shopAddress) {
        this.shopAddress = shopAddress == null ? null : shopAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.SHOP_TEL
     *
     * @return the value of SHOP_INFO.SHOP_TEL
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getShopTel() {
        return shopTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.SHOP_TEL
     *
     * @param shopTel the value for SHOP_INFO.SHOP_TEL
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setShopTel(String shopTel) {
        this.shopTel = shopTel == null ? null : shopTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.IS_SEND
     *
     * @return the value of SHOP_INFO.IS_SEND
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.IS_SEND
     *
     * @param isSend the value for SHOP_INFO.IS_SEND
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setIsSend(String isSend) {
        this.isSend = isSend == null ? null : isSend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.IMG_URL
     *
     * @return the value of SHOP_INFO.IMG_URL
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.IMG_URL
     *
     * @param imgUrl the value for SHOP_INFO.IMG_URL
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.GPS_X
     *
     * @return the value of SHOP_INFO.GPS_X
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public BigDecimal getGpsX() {
        return gpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.GPS_X
     *
     * @param gpsX the value for SHOP_INFO.GPS_X
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setGpsX(BigDecimal gpsX) {
        this.gpsX = gpsX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.GPS_Y
     *
     * @return the value of SHOP_INFO.GPS_Y
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public BigDecimal getGpsY() {
        return gpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.GPS_Y
     *
     * @param gpsY the value for SHOP_INFO.GPS_Y
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setGpsY(BigDecimal gpsY) {
        this.gpsY = gpsY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.STATE
     *
     * @return the value of SHOP_INFO.STATE
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.STATE
     *
     * @param state the value for SHOP_INFO.STATE
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.CREATE_USER_NAME
     *
     * @return the value of SHOP_INFO.CREATE_USER_NAME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.CREATE_USER_NAME
     *
     * @param createUserName the value for SHOP_INFO.CREATE_USER_NAME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.CREATE_TIME
     *
     * @return the value of SHOP_INFO.CREATE_TIME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.CREATE_TIME
     *
     * @param createTime the value for SHOP_INFO.CREATE_TIME
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.CREATE_USER_ID
     *
     * @return the value of SHOP_INFO.CREATE_USER_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.CREATE_USER_ID
     *
     * @param createUserId the value for SHOP_INFO.CREATE_USER_ID
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_INFO.AVG_RATE
     *
     * @return the value of SHOP_INFO.AVG_RATE
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public BigDecimal getAvgRate() {
        return avgRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_INFO.AVG_RATE
     *
     * @param avgRate the value for SHOP_INFO.AVG_RATE
     *
     * @mbggenerated Wed Jul 27 23:09:00 CST 2016
     */
    public void setAvgRate(BigDecimal avgRate) {
        this.avgRate = avgRate;
    }
}