package com.yaoyou.model.dataObject;

import org.codehaus.jackson.map.annotate.JsonSerialize;

import java.util.Date;
@JsonSerialize(include=JsonSerialize.Inclusion.NON_NULL)
public class ShopComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_COMMENT.COMMENT_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    private String commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_COMMENT.SHOP_INFO_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    private String shopInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_COMMENT.REMARK
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_COMMENT.RATE
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    private Integer rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_COMMENT.CREATE_USER_NAME
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    private String createUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_COMMENT.CREATE_TIME
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHOP_COMMENT.CREATE_USER_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    private String createUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_COMMENT.COMMENT_ID
     *
     * @return the value of SHOP_COMMENT.COMMENT_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_COMMENT.COMMENT_ID
     *
     * @param commentId the value for SHOP_COMMENT.COMMENT_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_COMMENT.SHOP_INFO_ID
     *
     * @return the value of SHOP_COMMENT.SHOP_INFO_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public String getShopInfoId() {
        return shopInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_COMMENT.SHOP_INFO_ID
     *
     * @param shopInfoId the value for SHOP_COMMENT.SHOP_INFO_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public void setShopInfoId(String shopInfoId) {
        this.shopInfoId = shopInfoId == null ? null : shopInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_COMMENT.REMARK
     *
     * @return the value of SHOP_COMMENT.REMARK
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_COMMENT.REMARK
     *
     * @param remark the value for SHOP_COMMENT.REMARK
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_COMMENT.RATE
     *
     * @return the value of SHOP_COMMENT.RATE
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public Integer getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_COMMENT.RATE
     *
     * @param rate the value for SHOP_COMMENT.RATE
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public void setRate(Integer rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_COMMENT.CREATE_USER_NAME
     *
     * @return the value of SHOP_COMMENT.CREATE_USER_NAME
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_COMMENT.CREATE_USER_NAME
     *
     * @param createUserName the value for SHOP_COMMENT.CREATE_USER_NAME
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_COMMENT.CREATE_TIME
     *
     * @return the value of SHOP_COMMENT.CREATE_TIME
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_COMMENT.CREATE_TIME
     *
     * @param createTime the value for SHOP_COMMENT.CREATE_TIME
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHOP_COMMENT.CREATE_USER_ID
     *
     * @return the value of SHOP_COMMENT.CREATE_USER_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHOP_COMMENT.CREATE_USER_ID
     *
     * @param createUserId the value for SHOP_COMMENT.CREATE_USER_ID
     *
     * @mbggenerated Thu Jul 28 11:24:57 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }
}