package com.yaoyou.model.dataObject;

import java.util.Date;

public class TimeTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIME_TABLE.ID
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIME_TABLE.REMIND_ID
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    private Integer remindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIME_TABLE.HH
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    private String hh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIME_TABLE.MM
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    private String mm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIME_TABLE.STATE
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TIME_TABLE.CREATE_TIME
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIME_TABLE.ID
     *
     * @return the value of TIME_TABLE.ID
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIME_TABLE.ID
     *
     * @param id the value for TIME_TABLE.ID
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIME_TABLE.REMIND_ID
     *
     * @return the value of TIME_TABLE.REMIND_ID
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public Integer getRemindId() {
        return remindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIME_TABLE.REMIND_ID
     *
     * @param remindId the value for TIME_TABLE.REMIND_ID
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public void setRemindId(Integer remindId) {
        this.remindId = remindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIME_TABLE.HH
     *
     * @return the value of TIME_TABLE.HH
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public String getHh() {
        return hh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIME_TABLE.HH
     *
     * @param hh the value for TIME_TABLE.HH
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public void setHh(String hh) {
        this.hh = hh == null ? null : hh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIME_TABLE.MM
     *
     * @return the value of TIME_TABLE.MM
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public String getMm() {
        return mm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIME_TABLE.MM
     *
     * @param mm the value for TIME_TABLE.MM
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public void setMm(String mm) {
        this.mm = mm == null ? null : mm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIME_TABLE.STATE
     *
     * @return the value of TIME_TABLE.STATE
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIME_TABLE.STATE
     *
     * @param state the value for TIME_TABLE.STATE
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TIME_TABLE.CREATE_TIME
     *
     * @return the value of TIME_TABLE.CREATE_TIME
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TIME_TABLE.CREATE_TIME
     *
     * @param createTime the value for TIME_TABLE.CREATE_TIME
     *
     * @mbggenerated Wed Aug 17 12:22:10 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}