package com.yaoyou.dao;

import com.yaoyou.model.dataObject.Activity;
import com.yaoyou.model.dataObject.ActivityExample.Criteria;
import com.yaoyou.model.dataObject.ActivityExample.Criterion;
import com.yaoyou.model.dataObject.ActivityExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ActivitySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String countByExample(ActivityExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("ACTIVITY");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String deleteByExample(ActivityExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("ACTIVITY");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String insertSelective(Activity record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("ACTIVITY");
        
        if (record.getActivityId() != null) {
            sql.VALUES("ACTIVITY_ID", "#{activityId,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.VALUES("TITLE", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.VALUES("TYPE", "#{type,jdbcType=VARCHAR}");
        }
        
        if (record.getBody() != null) {
            sql.VALUES("BODY", "#{body,jdbcType=VARCHAR}");
        }
        
        if (record.getImgUrl() != null) {
            sql.VALUES("IMG_URL", "#{imgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getBegTime() != null) {
            sql.VALUES("BEG_TIME", "#{begTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEndTime() != null) {
            sql.VALUES("END_TIME", "#{endTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getState() != null) {
            sql.VALUES("STATE", "#{state,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String selectByExample(ActivityExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ACTIVITY_ID");
        } else {
            sql.SELECT("ACTIVITY_ID");
        }
        sql.SELECT("TITLE");
        sql.SELECT("TYPE");
        sql.SELECT("BODY");
        sql.SELECT("IMG_URL");
        sql.SELECT("BEG_TIME");
        sql.SELECT("END_TIME");
        sql.SELECT("STATE");
        sql.SELECT("CREATE_TIME");
        sql.FROM("ACTIVITY");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Activity record = (Activity) parameter.get("record");
        ActivityExample example = (ActivityExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("ACTIVITY");
        
        if (record.getActivityId() != null) {
            sql.SET("ACTIVITY_ID = #{record.activityId,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            sql.SET("TITLE = #{record.title,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("TYPE = #{record.type,jdbcType=VARCHAR}");
        }
        
        if (record.getBody() != null) {
            sql.SET("BODY = #{record.body,jdbcType=VARCHAR}");
        }
        
        if (record.getImgUrl() != null) {
            sql.SET("IMG_URL = #{record.imgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getBegTime() != null) {
            sql.SET("BEG_TIME = #{record.begTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEndTime() != null) {
            sql.SET("END_TIME = #{record.endTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getState() != null) {
            sql.SET("STATE = #{record.state,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("ACTIVITY");
        
        sql.SET("ACTIVITY_ID = #{record.activityId,jdbcType=INTEGER}");
        sql.SET("TITLE = #{record.title,jdbcType=VARCHAR}");
        sql.SET("TYPE = #{record.type,jdbcType=VARCHAR}");
        sql.SET("BODY = #{record.body,jdbcType=VARCHAR}");
        sql.SET("IMG_URL = #{record.imgUrl,jdbcType=VARCHAR}");
        sql.SET("BEG_TIME = #{record.begTime,jdbcType=TIMESTAMP}");
        sql.SET("END_TIME = #{record.endTime,jdbcType=TIMESTAMP}");
        sql.SET("STATE = #{record.state,jdbcType=VARCHAR}");
        sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        
        ActivityExample example = (ActivityExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String updateByPrimaryKeySelective(Activity record) {
        SQL sql = new SQL();
        sql.UPDATE("ACTIVITY");
        
        if (record.getTitle() != null) {
            sql.SET("TITLE = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getType() != null) {
            sql.SET("TYPE = #{type,jdbcType=VARCHAR}");
        }
        
        if (record.getBody() != null) {
            sql.SET("BODY = #{body,jdbcType=VARCHAR}");
        }
        
        if (record.getImgUrl() != null) {
            sql.SET("IMG_URL = #{imgUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getBegTime() != null) {
            sql.SET("BEG_TIME = #{begTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getEndTime() != null) {
            sql.SET("END_TIME = #{endTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getState() != null) {
            sql.SET("STATE = #{state,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("ACTIVITY_ID = #{activityId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    protected void applyWhere(SQL sql, ActivityExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}