package com.yaoyou.dao;

import com.yaoyou.model.dataObject.ActivityShop;
import com.yaoyou.model.dataObject.ActivityShopExample.Criteria;
import com.yaoyou.model.dataObject.ActivityShopExample.Criterion;
import com.yaoyou.model.dataObject.ActivityShopExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ActivityShopSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String countByExample(ActivityShopExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("ACTIVITY_SHOP");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String deleteByExample(ActivityShopExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("ACTIVITY_SHOP");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String insertSelective(ActivityShop record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("ACTIVITY_SHOP");
        
        if (record.getActivityId() != null) {
            sql.VALUES("ACTIVITY_ID", "#{activityId,jdbcType=INTEGER}");
        }
        
        if (record.getShopInfoId() != null) {
            sql.VALUES("SHOP_INFO_ID", "#{shopInfoId,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String selectByExample(ActivityShopExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ACTIVITY_ID");
        } else {
            sql.SELECT("ACTIVITY_ID");
        }
        sql.SELECT("SHOP_INFO_ID");
        sql.SELECT("CREATE_TIME");
        sql.FROM("ACTIVITY_SHOP");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ActivityShop record = (ActivityShop) parameter.get("record");
        ActivityShopExample example = (ActivityShopExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("ACTIVITY_SHOP");
        
        if (record.getActivityId() != null) {
            sql.SET("ACTIVITY_ID = #{record.activityId,jdbcType=INTEGER}");
        }
        
        if (record.getShopInfoId() != null) {
            sql.SET("SHOP_INFO_ID = #{record.shopInfoId,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("ACTIVITY_SHOP");
        
        sql.SET("ACTIVITY_ID = #{record.activityId,jdbcType=INTEGER}");
        sql.SET("SHOP_INFO_ID = #{record.shopInfoId,jdbcType=VARCHAR}");
        sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        
        ActivityShopExample example = (ActivityShopExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    protected void applyWhere(SQL sql, ActivityShopExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}