package com.yaoyou.dao;

import com.yaoyou.model.dataObject.ActivityShop;
import com.yaoyou.model.dataObject.ActivityShopExample;
import java.util.List;

import com.yaoyou.model.dto.ShopActivityDTO;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface ActivityShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    @SelectProvider(type=ActivityShopSqlProvider.class, method="countByExample")
    int countByExample(ActivityShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    @DeleteProvider(type=ActivityShopSqlProvider.class, method="deleteByExample")
    int deleteByExample(ActivityShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    @Insert({
        "insert into ACTIVITY_SHOP (ACTIVITY_ID, SHOP_INFO_ID, ",
        "CREATE_TIME)",
        "values (#{activityId,jdbcType=INTEGER}, #{shopInfoId,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(ActivityShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    @InsertProvider(type=ActivityShopSqlProvider.class, method="insertSelective")
    int insertSelective(ActivityShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    @SelectProvider(type=ActivityShopSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ACTIVITY_ID", property="activityId", jdbcType=JdbcType.INTEGER),
        @Result(column="SHOP_INFO_ID", property="shopInfoId", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ActivityShop> selectByExample(ActivityShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    @UpdateProvider(type=ActivityShopSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ActivityShop record, @Param("example") ActivityShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY_SHOP
     *
     * @mbggenerated Fri Aug 26 09:03:10 CST 2016
     */
    @UpdateProvider(type=ActivityShopSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ActivityShop record, @Param("example") ActivityShopExample example);




    @Select({
            "select s.activity_id" ,
            "from activity_shop as s inner join activity as a on s.activity_id = a.activity_id ",
            "where shop_info_id = #{shopInfoId,jdbcType=VARCHAR} and END_TIME > CURRENT_TIMESTAMP()"
    })
    List<Integer> selectAvailableActivityIdByShopInfoId(String shopInfoId);

    String selectDTOStr = "select * ";

    String fromDTOStr = "from activity_shop " +
            "inner join shop_info as s on activity_shop.shop_info_id = s.shop_info_id ";

    @Select({
            selectDTOStr,
            fromDTOStr,
            "where activity_id = #{id,jdbcType=INTEGER}"
    })
    List<ShopActivityDTO> selectShopActivityDTO(int id);
}