package com.yaoyou.dao;

import com.yaoyou.model.dataObject.Cart;
import com.yaoyou.model.dataObject.CartExample;
import java.util.List;

import com.yaoyou.model.dto.CartSnap;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Tue Aug 09 08:54:07 CST 2016
     */
    @SelectProvider(type=CartSqlProvider.class, method="countByExample")
    int countByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Tue Aug 09 08:54:07 CST 2016
     */
    @DeleteProvider(type=CartSqlProvider.class, method="deleteByExample")
    int deleteByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Tue Aug 09 08:54:07 CST 2016
     */
    @Insert({
        "insert into CART (USER_ID, ITEM_ID, ",
        "COUNT, CREATE_TIME)",
        "values (#{userId,jdbcType=VARCHAR}, #{itemId,jdbcType=INTEGER}, ",
        "#{count,jdbcType=INTEGER}, #{createTime,jdbcType=TIMESTAMP})"
    })
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Tue Aug 09 08:54:07 CST 2016
     */
    @InsertProvider(type=CartSqlProvider.class, method="insertSelective")
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Tue Aug 09 08:54:07 CST 2016
     */
    @SelectProvider(type=CartSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="ITEM_ID", property="itemId", jdbcType=JdbcType.INTEGER),
        @Result(column="COUNT", property="count", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Cart> selectByExample(CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Tue Aug 09 08:54:07 CST 2016
     */
    @UpdateProvider(type=CartSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Cart record, @Param("example") CartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CART
     *
     * @mbggenerated Tue Aug 09 08:54:07 CST 2016
     */
    @UpdateProvider(type=CartSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Cart record, @Param("example") CartExample example);

    @Select({
            "select *",
            "from item",
            "LIMIT #{offset},#{limit}"
    })
    List<CartSnap> selectByLimit(@Param("offset") int offset, @Param("limit") int limit);

    @Select({
            "select CART.ITEM_ID, CART.COUNT, ITEM_SNAP.ITEM_SNAP_ID, ITEM_SNAP.PRICE",
            "from CART, ITEM_SNAP",
            "where USER_ID = #{userId,jdbcType=VARCHAR} and CART.ITEM_ID = ITEM_SNAP.ITEM_ID"
    })
    List<CartSnap> selectCartSnapByUserId(String userId);
}