package com.yaoyou.dao;

import com.yaoyou.model.dataObject.ItemSnap;
import com.yaoyou.model.dataObject.ItemSnapExample.Criteria;
import com.yaoyou.model.dataObject.ItemSnapExample.Criterion;
import com.yaoyou.model.dataObject.ItemSnapExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class ItemSnapSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    public String countByExample(ItemSnapExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("ITEM_SNAP");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    public String deleteByExample(ItemSnapExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("ITEM_SNAP");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    public String insertSelective(ItemSnap record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("ITEM_SNAP");
        
        if (record.getItemSnapId() != null) {
            sql.VALUES("ITEM_SNAP_ID", "#{itemSnapId,jdbcType=INTEGER}");
        }
        
        if (record.getItemId() != null) {
            sql.VALUES("ITEM_ID", "#{itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("PRICE", "#{price,jdbcType=DECIMAL}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("DESCRIPTION", "#{description,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    public String selectByExample(ItemSnapExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ITEM_SNAP_ID");
        } else {
            sql.SELECT("ITEM_SNAP_ID");
        }
        sql.SELECT("ITEM_ID");
        sql.SELECT("PRICE");
        sql.SELECT("DESCRIPTION");
        sql.FROM("ITEM_SNAP");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        ItemSnap record = (ItemSnap) parameter.get("record");
        ItemSnapExample example = (ItemSnapExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("ITEM_SNAP");
        
        if (record.getItemSnapId() != null) {
            sql.SET("ITEM_SNAP_ID = #{record.itemSnapId,jdbcType=INTEGER}");
        }
        
        if (record.getItemId() != null) {
            sql.SET("ITEM_ID = #{record.itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("PRICE = #{record.price,jdbcType=DECIMAL}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("DESCRIPTION = #{record.description,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("ITEM_SNAP");
        
        sql.SET("ITEM_SNAP_ID = #{record.itemSnapId,jdbcType=INTEGER}");
        sql.SET("ITEM_ID = #{record.itemId,jdbcType=VARCHAR}");
        sql.SET("PRICE = #{record.price,jdbcType=DECIMAL}");
        sql.SET("DESCRIPTION = #{record.description,jdbcType=VARCHAR}");
        
        ItemSnapExample example = (ItemSnapExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    public String updateByPrimaryKeySelective(ItemSnap record) {
        SQL sql = new SQL();
        sql.UPDATE("ITEM_SNAP");
        
        if (record.getItemId() != null) {
            sql.SET("ITEM_ID = #{itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("PRICE = #{price,jdbcType=DECIMAL}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("DESCRIPTION = #{description,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("ITEM_SNAP_ID = #{itemSnapId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_SNAP
     *
     * @mbggenerated Sun Aug 14 14:38:21 CST 2016
     */
    protected void applyWhere(SQL sql, ItemSnapExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}