package com.yaoyou.dao;

import com.yaoyou.model.dataObject.MedicineRemindRecord;
import com.yaoyou.model.dataObject.MedicineRemindRecordExample.Criteria;
import com.yaoyou.model.dataObject.MedicineRemindRecordExample.Criterion;
import com.yaoyou.model.dataObject.MedicineRemindRecordExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MedicineRemindRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String countByExample(MedicineRemindRecordExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("MEDICINE_REMIND_RECORD");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String deleteByExample(MedicineRemindRecordExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("MEDICINE_REMIND_RECORD");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String insertSelective(MedicineRemindRecord record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("MEDICINE_REMIND_RECORD");
        
        if (record.getId() != null) {
            sql.VALUES("ID", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("USER_ID", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            sql.VALUES("TIME", "#{time,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineName() != null) {
            sql.VALUES("MEDICINE_NAME", "#{medicineName,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String selectByExample(MedicineRemindRecordExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ID");
        } else {
            sql.SELECT("ID");
        }
        sql.SELECT("USER_ID");
        sql.SELECT("TIME");
        sql.SELECT("MEDICINE_NAME");
        sql.FROM("MEDICINE_REMIND_RECORD");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MedicineRemindRecord record = (MedicineRemindRecord) parameter.get("record");
        MedicineRemindRecordExample example = (MedicineRemindRecordExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("MEDICINE_REMIND_RECORD");
        
        if (record.getId() != null) {
            sql.SET("ID = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            sql.SET("TIME = #{record.time,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineName() != null) {
            sql.SET("MEDICINE_NAME = #{record.medicineName,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("MEDICINE_REMIND_RECORD");
        
        sql.SET("ID = #{record.id,jdbcType=INTEGER}");
        sql.SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("TIME = #{record.time,jdbcType=VARCHAR}");
        sql.SET("MEDICINE_NAME = #{record.medicineName,jdbcType=VARCHAR}");
        
        MedicineRemindRecordExample example = (MedicineRemindRecordExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    public String updateByPrimaryKeySelective(MedicineRemindRecord record) {
        SQL sql = new SQL();
        sql.UPDATE("MEDICINE_REMIND_RECORD");
        
        if (record.getUserId() != null) {
            sql.SET("USER_ID = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            sql.SET("TIME = #{time,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineName() != null) {
            sql.SET("MEDICINE_NAME = #{medicineName,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("ID = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_REMIND_RECORD
     *
     * @mbggenerated Fri Aug 19 17:50:34 CST 2016
     */
    protected void applyWhere(SQL sql, MedicineRemindRecordExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}