package com.yaoyou.dao;

import com.yaoyou.model.dataObject.IdRatePair;
import com.yaoyou.model.dataObject.MedicineComment;
import com.yaoyou.model.dataObject.MedicineCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface MedicineCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @SelectProvider(type=MedicineCommentSqlProvider.class, method="countByExample")
    int countByExample(MedicineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @DeleteProvider(type=MedicineCommentSqlProvider.class, method="deleteByExample")
    int deleteByExample(MedicineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @Delete({
        "delete from MEDICINE_COMMENT",
        "where COMMENT_ID = #{commentId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @Insert({
        "insert into MEDICINE_COMMENT (COMMENT_ID, MEDICINE_ID, ",
        "REMARK, RATE, CREATE_USER_NAME, ",
        "CREATE_TIME, CREATE_USER_ID)",
        "values (#{commentId,jdbcType=VARCHAR}, #{medicineId,jdbcType=VARCHAR}, ",
        "#{remark,jdbcType=VARCHAR}, #{rate,jdbcType=INTEGER}, #{createUserName,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{createUserId,jdbcType=VARCHAR})"
    })
    int insert(MedicineComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @InsertProvider(type=MedicineCommentSqlProvider.class, method="insertSelective")
    int insertSelective(MedicineComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @SelectProvider(type=MedicineCommentSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="COMMENT_ID", property="commentId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MEDICINE_ID", property="medicineId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="RATE", property="rate", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_USER_NAME", property="createUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_USER_ID", property="createUserId", jdbcType=JdbcType.VARCHAR)
    })
    List<MedicineComment> selectByExample(MedicineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @Select({
        "select",
        "COMMENT_ID, MEDICINE_ID, REMARK, RATE, CREATE_USER_NAME, CREATE_TIME, CREATE_USER_ID",
        "from MEDICINE_COMMENT",
        "where COMMENT_ID = #{commentId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="COMMENT_ID", property="commentId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="MEDICINE_ID", property="medicineId", jdbcType=JdbcType.VARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="RATE", property="rate", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_USER_NAME", property="createUserName", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CREATE_USER_ID", property="createUserId", jdbcType=JdbcType.VARCHAR)
    })
    MedicineComment selectByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @UpdateProvider(type=MedicineCommentSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") MedicineComment record, @Param("example") MedicineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @UpdateProvider(type=MedicineCommentSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") MedicineComment record, @Param("example") MedicineCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @UpdateProvider(type=MedicineCommentSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(MedicineComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    @Update({
        "update MEDICINE_COMMENT",
        "set MEDICINE_ID = #{medicineId,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
          "RATE = #{rate,jdbcType=INTEGER},",
          "CREATE_USER_NAME = #{createUserName,jdbcType=VARCHAR},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "CREATE_USER_ID = #{createUserId,jdbcType=VARCHAR}",
        "where COMMENT_ID = #{commentId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(MedicineComment record);

    @Select({
            "select",
            "COMMENT_ID, MEDICINE_ID, REMARK, RATE, CREATE_USER_NAME, CREATE_TIME, CREATE_USER_ID",
            "from MEDICINE_COMMENT",
            "where MEDICINE_ID = #{medicineId,jdbcType=VARCHAR}",
            "order by CREATE_TIME desc",
            "LIMIT #{offset},#{limit}"
    })
    @Results({
            @Result(column="COMMENT_ID", property="commentId", jdbcType=JdbcType.VARCHAR, id=true),
            @Result(column="MEDICINE_ID", property="medicineId", jdbcType=JdbcType.VARCHAR),
            @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
            @Result(column="RATE", property="rate", jdbcType=JdbcType.INTEGER),
            @Result(column="CREATE_USER_NAME", property="createUserName", jdbcType=JdbcType.VARCHAR),
            @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="CREATE_USER_ID", property="createUserId", jdbcType=JdbcType.VARCHAR)
    })
    List<MedicineComment> selectByLimit(@Param("medicineId") String commentId, @Param("offset") int offset, @Param("limit") int limit);

    @Select({
            "select MEDICINE_ID,AVG(RATE) R",
            "from MEDICINE_COMMENT",
            "GROUP BY MEDICINE_ID",
    })
    @Results({
            @Result(column="MEDICINE_ID", property="id", jdbcType=JdbcType.VARCHAR),
            @Result(column="R", property="rate", jdbcType=JdbcType.DECIMAL),
    })
    List<IdRatePair> selectAvgRateList();
}