package com.yaoyou.dao;

import com.yaoyou.model.dataObject.MedicineComment;
import com.yaoyou.model.dataObject.MedicineCommentExample.Criteria;
import com.yaoyou.model.dataObject.MedicineCommentExample.Criterion;
import com.yaoyou.model.dataObject.MedicineCommentExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MedicineCommentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    public String countByExample(MedicineCommentExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("MEDICINE_COMMENT");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    public String deleteByExample(MedicineCommentExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("MEDICINE_COMMENT");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    public String insertSelective(MedicineComment record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("MEDICINE_COMMENT");
        
        if (record.getCommentId() != null) {
            sql.VALUES("COMMENT_ID", "#{commentId,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineId() != null) {
            sql.VALUES("MEDICINE_ID", "#{medicineId,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("REMARK", "#{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getRate() != null) {
            sql.VALUES("RATE", "#{rate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateUserName() != null) {
            sql.VALUES("CREATE_USER_NAME", "#{createUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUserId() != null) {
            sql.VALUES("CREATE_USER_ID", "#{createUserId,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    public String selectByExample(MedicineCommentExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("COMMENT_ID");
        } else {
            sql.SELECT("COMMENT_ID");
        }
        sql.SELECT("MEDICINE_ID");
        sql.SELECT("REMARK");
        sql.SELECT("RATE");
        sql.SELECT("CREATE_USER_NAME");
        sql.SELECT("CREATE_TIME");
        sql.SELECT("CREATE_USER_ID");
        sql.FROM("MEDICINE_COMMENT");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MedicineComment record = (MedicineComment) parameter.get("record");
        MedicineCommentExample example = (MedicineCommentExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("MEDICINE_COMMENT");
        
        if (record.getCommentId() != null) {
            sql.SET("COMMENT_ID = #{record.commentId,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineId() != null) {
            sql.SET("MEDICINE_ID = #{record.medicineId,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("REMARK = #{record.remark,jdbcType=VARCHAR}");
        }
        
        if (record.getRate() != null) {
            sql.SET("RATE = #{record.rate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateUserName() != null) {
            sql.SET("CREATE_USER_NAME = #{record.createUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUserId() != null) {
            sql.SET("CREATE_USER_ID = #{record.createUserId,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("MEDICINE_COMMENT");
        
        sql.SET("COMMENT_ID = #{record.commentId,jdbcType=VARCHAR}");
        sql.SET("MEDICINE_ID = #{record.medicineId,jdbcType=VARCHAR}");
        sql.SET("REMARK = #{record.remark,jdbcType=VARCHAR}");
        sql.SET("RATE = #{record.rate,jdbcType=INTEGER}");
        sql.SET("CREATE_USER_NAME = #{record.createUserName,jdbcType=VARCHAR}");
        sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("CREATE_USER_ID = #{record.createUserId,jdbcType=VARCHAR}");
        
        MedicineCommentExample example = (MedicineCommentExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    public String updateByPrimaryKeySelective(MedicineComment record) {
        SQL sql = new SQL();
        sql.UPDATE("MEDICINE_COMMENT");
        
        if (record.getMedicineId() != null) {
            sql.SET("MEDICINE_ID = #{medicineId,jdbcType=VARCHAR}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("REMARK = #{remark,jdbcType=VARCHAR}");
        }
        
        if (record.getRate() != null) {
            sql.SET("RATE = #{rate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateUserName() != null) {
            sql.SET("CREATE_USER_NAME = #{createUserName,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCreateUserId() != null) {
            sql.SET("CREATE_USER_ID = #{createUserId,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("COMMENT_ID = #{commentId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDICINE_COMMENT
     *
     * @mbggenerated Wed Jul 27 09:55:40 CST 2016
     */
    protected void applyWhere(SQL sql, MedicineCommentExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}