package com.yaoyou.dao;

import com.yaoyou.model.dataObject.Order;
import com.yaoyou.model.dataObject.OrderExample;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface OrderMapper2 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @SelectProvider(type=OrderSqlProvider.class, method="countByExample")
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @DeleteProvider(type=OrderSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @Delete({
        "delete from T_ORDER",
        "where ORDER_ID = #{orderId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @Insert({
        "insert into T_ORDER (ORDER_ID, STATE, ",
        "USER_ID, TOTAL_PRICE, ",
        "PAY_ID, ADD_ID, DISTRIBUTION_ID, ",
        "CREATE_TIME)",
        "values (#{orderId,jdbcType=INTEGER}, #{state,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=VARCHAR}, #{totalPrice,jdbcType=DECIMAL}, ",
        "#{payId,jdbcType=INTEGER}, #{addId,jdbcType=INTEGER}, #{distributionId,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true, keyProperty="orderId")
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @InsertProvider(type=OrderSqlProvider.class, method="insertSelective")
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @SelectProvider(type=OrderSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="STATE", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOTAL_PRICE", property="totalPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_ID", property="payId", jdbcType=JdbcType.INTEGER),
        @Result(column="ADD_ID", property="addId", jdbcType=JdbcType.INTEGER),
        @Result(column="DISTRIBUTION_ID", property="distributionId", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @Select({
        "select",
        "ORDER_ID, STATE, USER_ID, TOTAL_PRICE, PAY_ID, ADD_ID, DISTRIBUTION_ID, CREATE_TIME",
        "from T_ORDER",
        "where ORDER_ID = #{orderId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="STATE", property="state", jdbcType=JdbcType.VARCHAR),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="TOTAL_PRICE", property="totalPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_ID", property="payId", jdbcType=JdbcType.INTEGER),
        @Result(column="ADD_ID", property="addId", jdbcType=JdbcType.INTEGER),
        @Result(column="DISTRIBUTION_ID", property="distributionId", jdbcType=JdbcType.INTEGER),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP)
    })
    Order selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @UpdateProvider(type=OrderSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ORDER
     *
     * @mbggenerated Sun Aug 07 21:54:45 CST 2016
     */
    @Update({
        "update T_ORDER",
        "set STATE = #{state,jdbcType=VARCHAR},",
          "USER_ID = #{userId,jdbcType=VARCHAR},",
          "TOTAL_PRICE = #{totalPrice,jdbcType=DECIMAL},",
          "PAY_ID = #{payId,jdbcType=INTEGER},",
          "ADD_ID = #{addId,jdbcType=INTEGER},",
          "DISTRIBUTION_ID = #{distributionId,jdbcType=INTEGER},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}",
        "where ORDER_ID = #{orderId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Order record);
}