package com.yaoyou.dao;

import com.yaoyou.model.dataObject.OrderItemSnap;
import com.yaoyou.model.dataObject.OrderItemSnapExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface OrderItemSnapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM_SNAP
     *
     * @mbggenerated Sun Aug 07 20:59:01 CST 2016
     */
    @SelectProvider(type=OrderItemSnapSqlProvider.class, method="countByExample")
    int countByExample(OrderItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM_SNAP
     *
     * @mbggenerated Sun Aug 07 20:59:01 CST 2016
     */
    @DeleteProvider(type=OrderItemSnapSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM_SNAP
     *
     * @mbggenerated Sun Aug 07 20:59:01 CST 2016
     */
    @Insert({
        "insert into ORDER_ITEM_SNAP (ORDER_ID, ITEM_SNAP_ID, ",
        "USER_ID)",
        "values (#{orderId,jdbcType=INTEGER}, #{itemSnapId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=VARCHAR})"
    })
    int insert(OrderItemSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM_SNAP
     *
     * @mbggenerated Sun Aug 07 20:59:01 CST 2016
     */
    @InsertProvider(type=OrderItemSnapSqlProvider.class, method="insertSelective")
    int insertSelective(OrderItemSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM_SNAP
     *
     * @mbggenerated Sun Aug 07 20:59:01 CST 2016
     */
    @SelectProvider(type=OrderItemSnapSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="ORDER_ID", property="orderId", jdbcType=JdbcType.INTEGER),
        @Result(column="ITEM_SNAP_ID", property="itemSnapId", jdbcType=JdbcType.INTEGER),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.VARCHAR)
    })
    List<OrderItemSnap> selectByExample(OrderItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM_SNAP
     *
     * @mbggenerated Sun Aug 07 20:59:01 CST 2016
     */
    @UpdateProvider(type=OrderItemSnapSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrderItemSnap record, @Param("example") OrderItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_ITEM_SNAP
     *
     * @mbggenerated Sun Aug 07 20:59:01 CST 2016
     */
    @UpdateProvider(type=OrderItemSnapSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrderItemSnap record, @Param("example") OrderItemSnapExample example);


}