package com.yaoyou.dao;

import com.yaoyou.model.dataObject.PicItemSnap;
import com.yaoyou.model.dataObject.PicItemSnapExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PicItemSnapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @SelectProvider(type=PicItemSnapSqlProvider.class, method="countByExample")
    int countByExample(PicItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @DeleteProvider(type=PicItemSnapSqlProvider.class, method="deleteByExample")
    int deleteByExample(PicItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Delete({
        "delete from PIC_ITEM_SNAP",
        "where PIC_ID = #{picId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Insert({
        "insert into PIC_ITEM_SNAP (PIC_ID, IMG_URL, ",
        "ITEM_SNAP_ID)",
        "values (#{picId,jdbcType=VARCHAR}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{itemSnapId,jdbcType=VARCHAR})"
    })
    int insert(PicItemSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @InsertProvider(type=PicItemSnapSqlProvider.class, method="insertSelective")
    int insertSelective(PicItemSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @SelectProvider(type=PicItemSnapSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PIC_ID", property="picId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="IMG_URL", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ITEM_SNAP_ID", property="itemSnapId", jdbcType=JdbcType.VARCHAR)
    })
    List<PicItemSnap> selectByExample(PicItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Select({
        "select",
        "PIC_ID, IMG_URL, ITEM_SNAP_ID",
        "from PIC_ITEM_SNAP",
        "where PIC_ID = #{picId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="PIC_ID", property="picId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="IMG_URL", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ITEM_SNAP_ID", property="itemSnapId", jdbcType=JdbcType.VARCHAR)
    })
    PicItemSnap selectByPrimaryKey(String picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @UpdateProvider(type=PicItemSnapSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PicItemSnap record, @Param("example") PicItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @UpdateProvider(type=PicItemSnapSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PicItemSnap record, @Param("example") PicItemSnapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @UpdateProvider(type=PicItemSnapSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PicItemSnap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_ITEM_SNAP
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Update({
        "update PIC_ITEM_SNAP",
        "set IMG_URL = #{imgUrl,jdbcType=VARCHAR},",
          "ITEM_SNAP_ID = #{itemSnapId,jdbcType=VARCHAR}",
        "where PIC_ID = #{picId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(PicItemSnap record);
}