package com.yaoyou.dao;

import com.yaoyou.model.dataObject.PicMedicine;
import com.yaoyou.model.dataObject.PicMedicineExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PicMedicineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @SelectProvider(type=PicMedicineSqlProvider.class, method="countByExample")
    int countByExample(PicMedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @DeleteProvider(type=PicMedicineSqlProvider.class, method="deleteByExample")
    int deleteByExample(PicMedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Delete({
        "delete from PIC_MEDICINE",
        "where PIC_ID = #{picId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Insert({
        "insert into PIC_MEDICINE (PIC_ID, IMG_URL, ",
        "MEDICINE_ID)",
        "values (#{picId,jdbcType=INTEGER}, #{imgUrl,jdbcType=VARCHAR}, ",
        "#{medicineId,jdbcType=VARCHAR})"
    })
    int insert(PicMedicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @InsertProvider(type=PicMedicineSqlProvider.class, method="insertSelective")
    int insertSelective(PicMedicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @SelectProvider(type=PicMedicineSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="PIC_ID", property="picId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="IMG_URL", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="MEDICINE_ID", property="medicineId", jdbcType=JdbcType.VARCHAR)
    })
    List<PicMedicine> selectByExample(PicMedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Select({
        "select",
        "PIC_ID, IMG_URL, MEDICINE_ID",
        "from PIC_MEDICINE",
        "where PIC_ID = #{picId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="PIC_ID", property="picId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="IMG_URL", property="imgUrl", jdbcType=JdbcType.VARCHAR),
        @Result(column="MEDICINE_ID", property="medicineId", jdbcType=JdbcType.VARCHAR)
    })
    PicMedicine selectByPrimaryKey(Integer picId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @UpdateProvider(type=PicMedicineSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PicMedicine record, @Param("example") PicMedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @UpdateProvider(type=PicMedicineSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PicMedicine record, @Param("example") PicMedicineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @UpdateProvider(type=PicMedicineSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PicMedicine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIC_MEDICINE
     *
     * @mbggenerated Mon Aug 01 13:55:00 CST 2016
     */
    @Update({
        "update PIC_MEDICINE",
        "set IMG_URL = #{imgUrl,jdbcType=VARCHAR},",
          "MEDICINE_ID = #{medicineId,jdbcType=VARCHAR}",
        "where PIC_ID = #{picId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(PicMedicine record);
}