package com.yaoyou.dao;

import com.yaoyou.model.dataObject.PointsNew;
import com.yaoyou.model.dataObject.PointsNewExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PointsNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @SelectProvider(type=PointsNewSqlProvider.class, method="countByExample")
    int countByExample(PointsNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @DeleteProvider(type=PointsNewSqlProvider.class, method="deleteByExample")
    int deleteByExample(PointsNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @Insert({
        "insert into points_new (OGR_FID, SHAPE, ",
        "osm_id, name, ",
        "barrier, highway, ",
        "ref, address, ",
        "is_in, place, ",
        "man_made, other_tags)",
        "values (#{ogrFid,jdbcType=INTEGER}, #{shape,jdbcType=BINARY}, ",
        "#{osmId,jdbcType=LONGVARCHAR}, #{name,jdbcType=LONGVARCHAR}, ",
        "#{barrier,jdbcType=LONGVARCHAR}, #{highway,jdbcType=LONGVARCHAR}, ",
        "#{ref,jdbcType=LONGVARCHAR}, #{address,jdbcType=LONGVARCHAR}, ",
        "#{isIn,jdbcType=LONGVARCHAR}, #{place,jdbcType=LONGVARCHAR}, ",
        "#{manMade,jdbcType=LONGVARCHAR}, #{otherTags,jdbcType=LONGVARCHAR})"
    })
    int insert(PointsNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @InsertProvider(type=PointsNewSqlProvider.class, method="insertSelective")
    int insertSelective(PointsNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @SelectProvider(type=PointsNewSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="OGR_FID", property="ogrFid", jdbcType=JdbcType.INTEGER),
        @Result(column="SHAPE", property="shape", jdbcType=JdbcType.BINARY),
        @Result(column="osm_id", property="osmId", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="barrier", property="barrier", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="highway", property="highway", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="ref", property="ref", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="is_in", property="isIn", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="place", property="place", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="man_made", property="manMade", jdbcType=JdbcType.LONGVARCHAR),
        @Result(column="other_tags", property="otherTags", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<PointsNew> selectByExampleWithBLOBs(PointsNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @SelectProvider(type=PointsNewSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="OGR_FID", property="ogrFid", jdbcType=JdbcType.INTEGER)
    })
    List<PointsNew> selectByExample(PointsNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @UpdateProvider(type=PointsNewSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PointsNew record, @Param("example") PointsNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @UpdateProvider(type=PointsNewSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") PointsNew record, @Param("example") PointsNewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    @UpdateProvider(type=PointsNewSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PointsNew record, @Param("example") PointsNewExample example);
}