package com.yaoyou.dao;

import com.yaoyou.model.dataObject.PointsNew;
import com.yaoyou.model.dataObject.PointsNewExample.Criteria;
import com.yaoyou.model.dataObject.PointsNewExample.Criterion;
import com.yaoyou.model.dataObject.PointsNewExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class PointsNewSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String countByExample(PointsNewExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("points_new");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String deleteByExample(PointsNewExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("points_new");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String insertSelective(PointsNew record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("points_new");
        
        if (record.getOgrFid() != null) {
            sql.VALUES("OGR_FID", "#{ogrFid,jdbcType=INTEGER}");
        }
        
        if (record.getShape() != null) {
            sql.VALUES("SHAPE", "#{shape,jdbcType=BINARY}");
        }
        
        if (record.getOsmId() != null) {
            sql.VALUES("osm_id", "#{osmId,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getBarrier() != null) {
            sql.VALUES("barrier", "#{barrier,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getHighway() != null) {
            sql.VALUES("highway", "#{highway,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getRef() != null) {
            sql.VALUES("ref", "#{ref,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.VALUES("address", "#{address,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getIsIn() != null) {
            sql.VALUES("is_in", "#{isIn,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getPlace() != null) {
            sql.VALUES("place", "#{place,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getManMade() != null) {
            sql.VALUES("man_made", "#{manMade,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getOtherTags() != null) {
            sql.VALUES("other_tags", "#{otherTags,jdbcType=LONGVARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String selectByExampleWithBLOBs(PointsNewExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("OGR_FID");
        } else {
            sql.SELECT("OGR_FID");
        }
        sql.SELECT("SHAPE");
        sql.SELECT("osm_id");
        sql.SELECT("name");
        sql.SELECT("barrier");
        sql.SELECT("highway");
        sql.SELECT("ref");
        sql.SELECT("address");
        sql.SELECT("is_in");
        sql.SELECT("place");
        sql.SELECT("man_made");
        sql.SELECT("other_tags");
        sql.FROM("points_new");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String selectByExample(PointsNewExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("OGR_FID");
        } else {
            sql.SELECT("OGR_FID");
        }
        sql.FROM("points_new");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        PointsNew record = (PointsNew) parameter.get("record");
        PointsNewExample example = (PointsNewExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("points_new");
        
        if (record.getOgrFid() != null) {
            sql.SET("OGR_FID = #{record.ogrFid,jdbcType=INTEGER}");
        }
        
        if (record.getShape() != null) {
            sql.SET("SHAPE = #{record.shape,jdbcType=BINARY}");
        }
        
        if (record.getOsmId() != null) {
            sql.SET("osm_id = #{record.osmId,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getBarrier() != null) {
            sql.SET("barrier = #{record.barrier,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getHighway() != null) {
            sql.SET("highway = #{record.highway,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getRef() != null) {
            sql.SET("ref = #{record.ref,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getAddress() != null) {
            sql.SET("address = #{record.address,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getIsIn() != null) {
            sql.SET("is_in = #{record.isIn,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getPlace() != null) {
            sql.SET("place = #{record.place,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getManMade() != null) {
            sql.SET("man_made = #{record.manMade,jdbcType=LONGVARCHAR}");
        }
        
        if (record.getOtherTags() != null) {
            sql.SET("other_tags = #{record.otherTags,jdbcType=LONGVARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("points_new");
        
        sql.SET("OGR_FID = #{record.ogrFid,jdbcType=INTEGER}");
        sql.SET("SHAPE = #{record.shape,jdbcType=BINARY}");
        sql.SET("osm_id = #{record.osmId,jdbcType=LONGVARCHAR}");
        sql.SET("name = #{record.name,jdbcType=LONGVARCHAR}");
        sql.SET("barrier = #{record.barrier,jdbcType=LONGVARCHAR}");
        sql.SET("highway = #{record.highway,jdbcType=LONGVARCHAR}");
        sql.SET("ref = #{record.ref,jdbcType=LONGVARCHAR}");
        sql.SET("address = #{record.address,jdbcType=LONGVARCHAR}");
        sql.SET("is_in = #{record.isIn,jdbcType=LONGVARCHAR}");
        sql.SET("place = #{record.place,jdbcType=LONGVARCHAR}");
        sql.SET("man_made = #{record.manMade,jdbcType=LONGVARCHAR}");
        sql.SET("other_tags = #{record.otherTags,jdbcType=LONGVARCHAR}");
        
        PointsNewExample example = (PointsNewExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("points_new");
        
        sql.SET("OGR_FID = #{record.ogrFid,jdbcType=INTEGER}");
        
        PointsNewExample example = (PointsNewExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_new
     *
     * @mbggenerated Wed Aug 17 19:46:29 CST 2016
     */
    protected void applyWhere(SQL sql, PointsNewExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}