package com.yaoyou.dao;

import com.yaoyou.model.dataObject.Remind;
import com.yaoyou.model.dataObject.RemindExample.Criteria;
import com.yaoyou.model.dataObject.RemindExample.Criterion;
import com.yaoyou.model.dataObject.RemindExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class RemindSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    public String countByExample(RemindExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("REMIND");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    public String deleteByExample(RemindExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("REMIND");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    public String insertSelective(Remind record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("REMIND");
        
        if (record.getRemindId() != null) {
            sql.VALUES("REMIND_ID", "#{remindId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("USER_ID", "#{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.VALUES("CREATOR", "#{creator,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("DESCRIPTION", "#{description,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineName() != null) {
            sql.VALUES("MEDICINE_NAME", "#{medicineName,jdbcType=VARCHAR}");
        }
        
        if (record.getDayFrequency() != null) {
            sql.VALUES("DAY_FREQUENCY", "#{dayFrequency,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("CREATE_TIME", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    public String selectByExample(RemindExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("REMIND_ID");
        } else {
            sql.SELECT("REMIND_ID");
        }
        sql.SELECT("USER_ID");
        sql.SELECT("CREATOR");
        sql.SELECT("DESCRIPTION");
        sql.SELECT("MEDICINE_NAME");
        sql.SELECT("DAY_FREQUENCY");
        sql.SELECT("CREATE_TIME");
        sql.FROM("REMIND");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Remind record = (Remind) parameter.get("record");
        RemindExample example = (RemindExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("REMIND");
        
        if (record.getRemindId() != null) {
            sql.SET("REMIND_ID = #{record.remindId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.SET("CREATOR = #{record.creator,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("DESCRIPTION = #{record.description,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineName() != null) {
            sql.SET("MEDICINE_NAME = #{record.medicineName,jdbcType=VARCHAR}");
        }
        
        if (record.getDayFrequency() != null) {
            sql.SET("DAY_FREQUENCY = #{record.dayFrequency,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("REMIND");
        
        sql.SET("REMIND_ID = #{record.remindId,jdbcType=INTEGER}");
        sql.SET("USER_ID = #{record.userId,jdbcType=VARCHAR}");
        sql.SET("CREATOR = #{record.creator,jdbcType=VARCHAR}");
        sql.SET("DESCRIPTION = #{record.description,jdbcType=VARCHAR}");
        sql.SET("MEDICINE_NAME = #{record.medicineName,jdbcType=VARCHAR}");
        sql.SET("DAY_FREQUENCY = #{record.dayFrequency,jdbcType=VARCHAR}");
        sql.SET("CREATE_TIME = #{record.createTime,jdbcType=TIMESTAMP}");
        
        RemindExample example = (RemindExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    public String updateByPrimaryKeySelective(Remind record) {
        SQL sql = new SQL();
        sql.UPDATE("REMIND");
        
        if (record.getUserId() != null) {
            sql.SET("USER_ID = #{userId,jdbcType=VARCHAR}");
        }
        
        if (record.getCreator() != null) {
            sql.SET("CREATOR = #{creator,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("DESCRIPTION = #{description,jdbcType=VARCHAR}");
        }
        
        if (record.getMedicineName() != null) {
            sql.SET("MEDICINE_NAME = #{medicineName,jdbcType=VARCHAR}");
        }
        
        if (record.getDayFrequency() != null) {
            sql.SET("DAY_FREQUENCY = #{dayFrequency,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("CREATE_TIME = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("REMIND_ID = #{remindId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REMIND
     *
     * @mbggenerated Thu Aug 18 08:50:19 CST 2016
     */
    protected void applyWhere(SQL sql, RemindExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}